import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

type Binding = Record<string, unknown>
type RawCatalog = Record<string, { name: { ar: string; en: string }; riwayat: Record<string, { styles: Record<string, { providers: Record<string, Binding[]> }> }> }>
type Source = { id: string; provider: string; label: string; binding: Binding }
type Leaf = { reciter: string; name: { ar: string; en: string }; riwayah: string; style: string; sources: Source[] }

const output = fileURLToPath(new URL('../src/generated/', import.meta.url))
const catalogPath = fileURLToPath(new URL('../data/catalog.json', import.meta.url))
const reserved = new Set(['await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do', 'else', 'enum', 'export', 'extends', 'false', 'finally', 'for', 'function', 'if', 'implements', 'import', 'in', 'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private', 'protected', 'public', 'return', 'super', 'switch', 'static', 'this', 'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'yield'])
// Deliberate policy, not catalog-frequency order. Add new riwayat explicitly here.
const frozenRiwayahPriority = ['hafs', 'warsh_an_nafi', 'albazzi_and_qunbul_an_ibnkatheer', 'albazzi_an_ibnkatheer', 'aldouri_an_abiamr', 'aldouri_an_alkisai', 'alsusi_an_abiamr', 'hisham_an_ibnamer', 'ibndhakwan_an_ibnamer', 'ibnjammaz_an_abijaafar', 'khalaf_an_hamzah', 'qalun_an_nafi', 'qalun_an_nafi_tariq_abinasheet', 'qunbul_an_ibnkatheer', 'ruways_and_rawh_an_yaqoub_alhadrami', 'shubah_an_asim', 'warsh_an_nafi_tariq_abibakr_alasbahani', 'warsh_an_nafi_tariq_alazraq'] as const
const frozenStylePriority = ['murattal', 'mujawwad', 'muallim', 'kids_repeat'] as const

function pascalCase(value: string): string {
  const result = value.split(/[^A-Za-z0-9]+/).filter(Boolean).map(part => part[0]!.toUpperCase() + part.slice(1)).join('')
  if (!result || /^[0-9]/.test(result) || reserved.has(result.toLowerCase())) throw new Error(`Unsafe generated key: ${value}`)
  return result
}
function quote(value: unknown): string { return JSON.stringify(value, null, 2) }
function sourceId(provider: string, binding: Binding): string {
  const key = provider === 'mp3Quran' ? binding.moshafId : provider === 'everyAyah' ? binding.everyAyahId : binding.id
  if ((typeof key !== 'string' && typeof key !== 'number') || key === '') throw new Error(`Missing binding key for ${provider}`)
  return `${provider}:${key}`
}
function label(provider: string, binding: Binding): string {
  if (provider === 'mp3Quran') return typeof binding.moshafName === 'string' ? binding.moshafName : `Moshaf ${binding.moshafId}`
  if (provider === 'everyAyah') return typeof binding.name === 'string' ? binding.name : `EveryAyah ${binding.everyAyahId}`
  return `Recitation ${binding.id}`
}
function cleanBinding(provider: string, binding: Binding): Binding {
  if (provider === 'mp3Quran') return { moshafId: binding.moshafId, server: binding.server, surahList: binding.surahList, surahTotal: binding.surahTotal }
  if (provider === 'everyAyah') return { everyAyahId: binding.everyAyahId, subfolder: binding.subfolder, bitrate: binding.bitrate }
  return { id: binding.id }
}
function renderIds(reciters: string[], riwayat: string[], styles: string[], providers: string[], leaves: Leaf[], sourceIds: string[]): string {
  const union = (values: string[]) => values.map(quote).join(' | ')
  return `/* generated by scripts/generate.ts; do not edit */\nexport type ReciterId = ${union(reciters)}\nexport type RiwayahId = ${union(riwayat)}\nexport type StyleId = ${union(styles)}\nexport type ProviderId = ${union(providers)}\nexport type SourceId = ${union(sourceIds)}\nexport type ValidRecordingClassRef = ${leaves.map(l => `{ readonly kind: 'recordingClass'; readonly reciter: ${quote(l.reciter)}; readonly riwayah: ${quote(l.riwayah)}; readonly style: ${quote(l.style)} }`).join(' | ')}\nexport const Riwayah = ${quote(Object.fromEntries(riwayat.map(id => [pascalCase(id), id])))} as const satisfies Record<string, RiwayahId>\nexport const Style = ${quote(Object.fromEntries(styles.map(id => [pascalCase(id), id])))} as const satisfies Record<string, StyleId>\n`
}
function renderCatalog(leaves: Leaf[]): string {
  return `/* generated by scripts/generate.ts; do not edit */\nexport interface GeneratedSource { readonly id: string; readonly provider: string; readonly label: string; readonly binding: Readonly<Record<string, unknown>> }\nexport interface GeneratedLeaf { readonly reciter: string; readonly name: { readonly ar: string; readonly en: string }; readonly riwayah: string; readonly style: string; readonly sources: readonly GeneratedSource[] }\nexport const catalog = ${quote(leaves)} as const satisfies readonly GeneratedLeaf[]\n`
}
function renderRecordings(leaves: Leaf[]): string {
  const grouped = new Map<string, Map<string, Map<string, Leaf>>>()
  for (const leaf of leaves) {
    const byRiwayah = grouped.get(leaf.reciter) ?? new Map<string, Map<string, Leaf>>(); grouped.set(leaf.reciter, byRiwayah)
    const byStyle = byRiwayah.get(leaf.riwayah) ?? new Map<string, Leaf>(); byRiwayah.set(leaf.riwayah, byStyle); byStyle.set(leaf.style, leaf)
  }
  const tree = [...grouped.entries()].map(([reciter, riwayat]) => {
    const reciterKey = pascalCase(reciter)
    const first = riwayat.values().next().value as Map<string, Leaf>
    const firstLeaf = first.values().next().value as Leaf | undefined
    if (!firstLeaf) throw new Error(`Empty reciter branch: ${reciter}`)
    const name = firstLeaf.name
    const riwayahProperties = [...riwayat.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([riwayah, styles]) => `${quote(pascalCase(riwayah))}: {${[...styles.values()].sort((a,b) => a.style.localeCompare(b.style)).map(leaf => `${quote(pascalCase(leaf.style))}: { kind: 'recordingClass', reciter: ${quote(leaf.reciter)}, riwayah: ${quote(leaf.riwayah)}, style: ${quote(leaf.style)} }`).join(',')}}`).join(',')
    return `${quote(reciterKey)}: { kind: 'reciter', id: ${quote(reciter)}, name: ${quote(name)}, ${riwayahProperties} }`
  }).join(',\n')
  return `/* generated by scripts/generate.ts; do not edit */\nimport type { ReciterNode } from '../domain/refs.js'\nexport const Reciters = {\n${tree}\n} as const satisfies Record<string, ReciterNode>\n`
}
const raw = JSON.parse(await readFile(catalogPath, 'utf8')) as RawCatalog
const leaves: Leaf[] = []
for (const [reciter, reciterValue] of Object.entries(raw)) {
  if (Object.keys(reciterValue.riwayat).length === 0) throw new Error(`Empty reciter branch: ${reciter}`)
  for (const [riwayah, riwayahValue] of Object.entries(reciterValue.riwayat)) {
    if (Object.keys(riwayahValue.styles).length === 0) throw new Error(`Empty riwayah branch: ${reciter}/${riwayah}`)
    for (const [style, styleValue] of Object.entries(riwayahValue.styles)) {
      if (riwayah === 'none' || style === 'translation') continue
      const sources: Source[] = []
      for (const [provider, bindings] of Object.entries(styleValue.providers)) for (const binding of bindings) sources.push({ id: sourceId(provider, binding), provider, label: label(provider, binding), binding: cleanBinding(provider, binding) })
      if (sources.length === 0) throw new Error(`Empty provider branch: ${reciter}/${riwayah}/${style}`)
      leaves.push({ reciter, name: reciterValue.name, riwayah, style, sources })
    }
  }
}
if (leaves.length === 0) throw new Error('Public projection is empty')
const reciters = [...new Set(leaves.map(x => x.reciter))].sort()
const riwayat = [...new Set(leaves.map(x => x.riwayah))].sort()
const styles = [...new Set(leaves.map(x => x.style))].sort()
const providers = [...new Set(leaves.flatMap(x => x.sources.map(y => y.provider)))].sort()
const sourceIds = leaves.flatMap(x => x.sources.map(y => y.id)).sort()
if (new Set(sourceIds).size !== sourceIds.length) throw new Error('Duplicate SourceId in catalog')
for (const values of [reciters, riwayat, styles]) { const seen = new Map<string, string>(); for (const value of values) { const key = pascalCase(value); const prior = seen.get(key); if (prior) throw new Error(`PascalCase collision: ${prior} and ${value} -> ${key}`); seen.set(key, value) } }
for (const riwayah of riwayat) if (!frozenRiwayahPriority.includes(riwayah as never)) throw new Error(`Riwayah ${riwayah} is absent from the frozen priority list`)
for (const style of styles) if (!frozenStylePriority.includes(style as never)) throw new Error(`Style ${style} is absent from the frozen priority list`)
const files: Record<string, string> = {
  'ids.ts': renderIds(reciters, riwayat, styles, providers, leaves, sourceIds),
  'catalog.data.ts': renderCatalog(leaves),
  'recordings.ts': renderRecordings(leaves),
  'priority.ts': `/* generated by scripts/generate.ts; do not edit */\nimport type { RiwayahId, StyleId } from './ids.js'\nexport const RIWAYAH_PRIORITY = ${quote(frozenRiwayahPriority)} as const satisfies readonly RiwayahId[]\nexport const STYLE_PRIORITY = ${quote(frozenStylePriority)} as const satisfies readonly StyleId[]\n`,
}
if (process.argv.includes('--check')) {
  for (const [name, generated] of Object.entries(files)) {
    let existing: string | undefined; try { existing = await readFile(new URL(name, `file://${output}`).pathname, 'utf8') } catch { /* fail below */ }
    if (existing !== generated) throw new Error(`Generated file differs: src/generated/${name}; run pnpm gen.`)
  }
} else { await mkdir(output, { recursive: true }); await Promise.all(Object.entries(files).map(([name, contents]) => writeFile(new URL(name, `file://${output}`).pathname, contents))) }
