export { queryCatalog } from './catalog/query.js'
export { getReciters, getRiwayat, getStyles } from './catalog/facets.js'
export { getAyah, getAyahs, getSurah, createAudioRouter, resetDefaultClient } from './runtime/client.js'
export { Reciters } from './generated/recordings.js'
export { Riwayah, Style } from './generated/ids.js'
export type { ReciterId, RiwayahId, StyleId, ProviderId, SourceId, ReciterRef, RecordingClassRef, SourceRef, ReciterNode } from './domain/refs.js'
export type { Granularity, Representation, Capability } from './domain/capability.js'
export type { AudioResult, AudioSource, AudioRoute, ProviderAttempt } from './domain/result.js'
export type { ProviderTraceEvent, ProviderTraceHook } from './domain/trace.js'
export type { AyahRequest, AyahRangeRequest, SurahRequest, CommonOptions } from './domain/selection.js'
export type { CatalogQuery, CatalogQueryResult, RecordingClassSummary, SourceSummary } from './catalog/query.js'
export type { AudioRouterConfig, QuranFoundationConfig } from './runtime/config.js'
export { RqaError, RecordingClassNotFoundError, SourceNotFoundError, ReciterNotFoundError, InvalidRequestError, RepresentationUnavailableError, ResourceUnavailableError, NoEligibleProviderError, ProviderNotConfiguredError, BrowserCredentialError, AllProvidersFailedError, ProviderHttpError, ProviderResponseError } from './domain/errors.js'
