import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { Highlight, themes } from 'prism-react-renderer'
import { getAyah, getAyahs, getSurah, queryCatalog, Reciters, type AudioResult, type AudioSource, type RecordingClassRef, type SourceRef, type ReciterId, type RiwayahId, type StyleId , type SourceSummary } from 'quranic-audio-router'

type RunState = { value?: unknown; error?: unknown; elapsedMs?: number }
const catalog = queryCatalog()
const husary = Reciters.MahmoudAlhusary.Hafs.Murattal
const husarySources = queryCatalog({ reciter: husary.reciter, riwayah: husary.riwayah, style: husary.style }).sources
const minshawi = queryCatalog({ reciter: 'muhammad_alminshawi', riwayah: 'hafs', style: 'murattal' }).classes[0]!
const minshawi1387 = queryCatalog({ reciter: minshawi.reciter, riwayah: minshawi.riwayah, style: minshawi.style, provider: 'mp3Quran' }).sources.find(source => source.id === 'mp3Quran:10924')!
const everyOnly = catalog.classes.find(recording => queryCatalog({ reciter: recording.reciter, riwayah: recording.riwayah, style: recording.style }).sources.every(source => source.provider === 'everyAyah'))!
const mpOnly = catalog.classes.find(recording => queryCatalog({ reciter: recording.reciter, riwayah: recording.riwayah, style: recording.style }).sources.every(source => source.provider === 'mp3Quran'))!
const featured = catalog.reciters.filter(reciter => queryCatalog({ reciter }).riwayat.length > 1).slice(0, 15)
const toJson = (value: unknown) => JSON.stringify(value, (_key, item) => item instanceof Error ? { name: item.name, code: (item as { code?: string }).code, message: item.message } : item, 2)

function Code({ children }: { children: string }) { return <Highlight code={children} language="typescript" theme={themes.nightOwl}>{({ style, tokens, getLineProps, getTokenProps }) => <div className="code"><pre style={style}>{tokens.map((line, i) => <div key={i} {...getLineProps({ line })}>{line.map((token, j) => <span key={j} {...getTokenProps({ token })} />)}</div>)}</pre></div>}</Highlight> }
function JsonTree({ value }: { value: unknown }) { return <div className="json"><details open><summary>Returned object</summary><pre>{toJson(value)}</pre></details></div> }
function Section({ number, title, children }: { number: string; title: string; children: ReactNode }) { return <section id={`section-${number}`}><div className="section-head"><div className="number">{number}</div><h2>{title}</h2></div>{children}</section> }
function run(set: (state: RunState) => void, action: () => Promise<unknown> | unknown) { const start = performance.now(); return Promise.resolve(action()).then(value => set({ value, elapsedMs: Math.round(performance.now() - start) }), error => set({ error, elapsedMs: Math.round(performance.now() - start) })) }
function RunCard({ title, code, action, children }: { title: string; code: string; action: () => Promise<unknown> | unknown; children?: ReactNode }) { const [state, setState] = useState<RunState>(); const [busy, setBusy] = useState(false); async function execute() { setBusy(true); await run(setState, action); setBusy(false) } return <div className="card"><h3>{title}</h3>{children}<Code>{code}</Code><button className="run" onClick={execute} disabled={busy}>{busy ? 'Running…' : 'Run'}</button>{state && <><p className={state.error ? 'error' : ''}>{state.error ? `${(state.error as Error).name}: ${(state.error as Error).message}` : `${state.elapsedMs} ms`}</p><JsonTree value={state.error ?? state.value} /></>}</div> }
function ApiCard({ title, signature, label, initial, execute }: { title: string; signature: string; label: string; initial: string; execute: (input: string) => Promise<unknown> | unknown }) { const [input, setInput] = useState(initial); const [state, setState] = useState<RunState>(); const [busy, setBusy] = useState(false); async function runIt() { setBusy(true); await run(setState, () => execute(input)); setBusy(false) } return <div className="card"><h3>{title}</h3><Code>{signature}</Code><label>{label}<input value={input} onChange={event => setInput(event.target.value)} /></label><button className="run" onClick={runIt} disabled={busy}>{busy ? 'Running…' : 'Run'}</button>{state && <><p className={state.error ? 'error' : ''}>{state.error ? `${(state.error as Error).name}: ${(state.error as Error).message}` : `${state.elapsedMs} ms`}</p><JsonTree value={state.error ?? state.value} /></>}</div> }
function SegmentAudio({ source }: { source: AudioSource }) { const audio = useRef<HTMLAudioElement>(null); useEffect(() => { if (source.granularity !== 'ayah' || source.representation !== 'segment') return; const node = audio.current; if (!node) return; const loaded = () => { node.currentTime = source.startMs / 1000 }; const tick = () => { if (node.currentTime >= source.endMs / 1000) node.pause() }; node.addEventListener('loadedmetadata', loaded); node.addEventListener('timeupdate', tick); return () => { node.removeEventListener('loadedmetadata', loaded); node.removeEventListener('timeupdate', tick) } }, [source]); return <><audio className="audio" controls ref={audio} src={source.url} /><p className="small">{source.granularity === 'ayah' && source.representation === 'segment' ? 'Approximate segment playback — browser stop timing can overshoot.' : 'Standalone provider media.'}</p></> }
function MatrixRow({ label, code, action }: { label: string; code: string; action: () => Promise<unknown> }) { const [state, setState] = useState<RunState>(); const [busy, setBusy] = useState(false); async function execute() { setBusy(true); await run(setState, action); setBusy(false) } return <div className="matrix-row"><div><strong>{label}</strong><br /><code>{code}</code></div><div className="result">{state && (state.error ? <span className="error">{(state.error as { code?: string }).code ?? (state.error as Error).name}: {(state.error as Error).message}</span> : 'Resolved successfully')}</div><button className="run" onClick={execute} disabled={busy}>{busy ? '…' : 'Run'}</button></div> }
const PROVIDER_LABEL = { everyAyah: 'EveryAyah', mp3Quran: 'MP3Quran', quranFoundationAyah: 'Quran Foundation · ayah API', quranFoundationSurah: 'Quran Foundation · surah API' } as const
function Vocabulary({ provider, sources }: { provider: keyof typeof PROVIDER_LABEL; sources: readonly SourceSummary[] }) {
  return <div className="binding"><span className="tag">{PROVIDER_LABEL[provider]}</span>{sources.map(source => <div key={source.id} className="vocab"><code>{source.id}</code><dl>{Object.entries(source.providerMetadata).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value).length > 60 ? String(value).slice(0, 57) + '…' : String(value)}</dd></div>)}</dl></div>)}</div>
}
function Picker() { const [reciterId, setReciterId] = useState<ReciterId>(husary.reciter); const [riwayah, setRiwayah] = useState<RiwayahId>(husary.riwayah); const [style, setStyle] = useState<StyleId>(husary.style); const [ayah, setAyah] = useState('1:2'); const [state, setState] = useState<RunState>(); const riwayat = useMemo(() => queryCatalog({ reciter: reciterId }).riwayat, [reciterId]); const styles = useMemo(() => queryCatalog({ reciter: reciterId, riwayah }).styles, [reciterId, riwayah]); useEffect(() => { if (!riwayat.includes(riwayah)) setRiwayah(riwayat[0]!) }, [riwayat, riwayah]); useEffect(() => { if (!styles.includes(style)) setStyle(styles[0]!) }, [styles, style]); const source = (state?.value as AudioResult | undefined)?.sources[0]; async function execute() { await run(setState, () => getAyah({ ayah, recording: { kind: 'recordingClass', reciter: reciterId, riwayah, style } as never })) } return <div className="picker"><div className="card"><div className="controls"><label>Reciter<select value={reciterId} onChange={event => setReciterId(event.target.value as ReciterId)}>{catalog.reciters.map(item => <option key={item.id} value={item.id}>{item.name.en}</option>)}</select></label><label>Riwayah{riwayat.length === 1 ? <div className="fixed">{riwayat[0]}</div> : <select value={riwayah} onChange={event => setRiwayah(event.target.value as RiwayahId)}>{riwayat.map(item => <option key={item}>{item}</option>)}</select>}</label><label>Style{styles.length === 1 ? <div className="fixed">{styles[0]}</div> : <select value={style} onChange={event => setStyle(event.target.value as StyleId)}>{styles.map(item => <option key={item}>{item}</option>)}</select>}</label><label>Ayah<input value={ayah} onChange={event => setAyah(event.target.value)} /></label></div><button className="run" onClick={execute}>Resolve audio</button><p className="small">Featured multi-riwayah reciters</p><div className="featured">{featured.map(item => <button key={item.id} onClick={() => setReciterId(item.id)}>{item.name.en}</button>)}</div>{state && <><JsonTree value={state.error ?? state.value} />{source && <SegmentAudio source={source} />}</>}</div><aside className="card"><h3>Discovery mechanics</h3><Code>{`queryCatalog().reciters\nqueryCatalog({ reciter: '${reciterId}' }).riwayat\nqueryCatalog({ reciter: '${reciterId}', riwayah: '${riwayah}' }).styles`}</Code><p>Single-option branches resolve to fixed labels; only real choices become dropdowns.</p><span className="tag warn">QF panes not yet implemented</span></aside></div> }

export function App() { return <><header className="hero"><div className="shell"><div className="eyebrow">Interactive documentation · browser-safe</div><h1>One catalog.<br />Many audio domains.</h1><p>A live consumer of the browser-safe SDK. Every provider request starts only after you press Run.</p><nav className="nav">{['Catalog', 'API', 'Matrix', 'Picker', 'Before / after', 'Start'].map((item, index) => <a key={item} href={`#section-${index + 1}`}>{item}</a>)}</nav></div></header><main className="shell">
<Section number="1" title="The catalog is the backbone"><p>Counts are derived live from <code>queryCatalog()</code>.</p><div className="grid three">{[[catalog.reciters.length, 'reciters'], [catalog.classes.length, 'recording classes'], [catalog.riwayat.length, 'riwayat'], [catalog.styles.length, 'styles']].map(([value, label]) => <div className="card stat" key={String(label)}>{value}<span>{label}</span></div>)}</div><div className="card"><h3>Mahmoud Al-Husary · Hafs · Murattal</h3><p>One recording class served by provider domains; the catalog does not claim the media itself is identical.</p><Code>{`const recording = Reciters.MahmoudAlhusary.Hafs.Murattal`}</Code><div className="grid two">{(['quranFoundationAyah', 'quranFoundationSurah', 'mp3Quran', 'everyAyah'] as const).map(provider => <Vocabulary key={provider} provider={provider} sources={husarySources.filter(source => source.provider === provider)} />)}</div><p className="note">Both Quran Foundation entries are <code>id 6</code>. They are <strong>different ID spaces that collide on one integer</strong>: crossing them gives a different reciter. That is the whole reason this package exists. Audio resolution through QF is not implemented yet; its vocabulary above is catalog data.</p></div></Section>
<Section number="2" title="API reference, executed"><div className="grid two"><ApiCard title="queryCatalog" signature={`queryCatalog({ reciter })`} label="Reciter" initial="mahmoud_alhusary" execute={reciter => queryCatalog({ reciter: reciter as never })} /><ApiCard title="getAyah" signature={`getAyah({ ayah, reciter })`} label="Verse key" initial="1:2" execute={ayah => getAyah({ ayah, reciter: 'mahmoud_alhusary' })} /><ApiCard title="getAyahs" signature={`getAyahs({ from, to, reciter })`} label="Range, comma-separated" initial="1:1,1:3" execute={input => { const [from, to] = input.split(','); return getAyahs({ from: from?.trim() ?? '', to: to?.trim() ?? '', reciter: 'mahmoud_alhusary' }) }} /><ApiCard title="getSurah" signature={`getSurah({ surah, recording })`} label="Surah" initial="1" execute={input => getSurah({ surah: Number(input), recording: husary })} /></div></Section>
<Section number="3" title="Return-shape matrix"><p>Intentional errors are runnable, too.</p><div className="matrix">{[['Class pin', `getAyah({ ayah: '1:2', recording: husary })`, () => getAyah({ ayah: '1:2', recording: husary })], ['Loose reciter', `getAyah({ ayah: '1:2', reciter: 'mahmoud_alhusary' })`, () => getAyah({ ayah: '1:2', reciter: 'mahmoud_alhusary' })], ['Source pin', `getAyah({ ayah: '1:2', source })`, () => getAyah({ ayah: '1:2', source: husarySources[0] as SourceRef })], ['Segment', `getAyah({ ayah: '1:2', reciter: 'mahmoud_alhusary', representation: 'segment' })`, () => getAyah({ ayah: '1:2', reciter: 'mahmoud_alhusary', representation: 'segment' })], ['All alternatives', `getAyah({ ayah: '1:2', reciter: 'mahmoud_alhusary', alternatives: 'all' })`, () => getAyah({ ayah: '1:2', reciter: 'mahmoud_alhusary', alternatives: 'all' })], ['N-source range', `getAyahs({ from: '1:1', to: '1:3', reciter: 'mahmoud_alhusary' })`, () => getAyahs({ from: '1:1', to: '1:3', reciter: 'mahmoud_alhusary' })], ['Cross-surah error', `getAyahs({ from: '1:7', to: '2:1', reciter: 'mahmoud_alhusary' })`, () => getAyahs({ from: '1:7', to: '2:1', reciter: 'mahmoud_alhusary' })], ['Static availability', `getSurah({ surah: 55, source: minshawi1387 })`, () => getSurah({ surah: 55, source: minshawi1387 as SourceRef })], ['Representation error', `getAyah({ ayah: '1:2', recording: everyOnly, representation: 'segment' })`, () => getAyah({ ayah: '1:2', recording: everyOnly as RecordingClassRef, representation: 'segment' })]].map(([label, code, action]) => <MatrixRow key={label as string} label={label as string} code={code as string} action={action as () => Promise<unknown>} />)}</div><div className="card muted"><span className="tag warn">Quran Foundation not yet implemented</span><p>No simulated response or fixture is rendered.</p></div></Section>
<Section number="4" title="Pick by real catalog facets"><Picker /></Section>
<Section number="5" title="Before / after"><p>Fallback is not magic: 249 public classes are MP3Quran-only, so it contributes nothing for most recordings.</p><div className="grid two"><RunCard title="EveryAyah ayah URL" code={`// Before: direct EveryAyah URL\ngetAyah({ ayah: '1:2', recording: husary })`} action={() => getAyah({ ayah: '1:2', recording: husary })}><p>Nearly as simple as the SDK. Network calls made: <b>0</b>.</p></RunCard><RunCard title="MP3Quran surah URL" code={`// Before: server + '001.mp3'\ngetSurah({ surah: 1, recording: husary })`} action={() => getSurah({ surah: 1, recording: husary })}><p>Also direct and zero-call. Network calls made: <b>0</b>.</p></RunCard><RunCard title="MP3Quran timing" code={`getAyah({ ayah: '9:129', reciter: 'muhammad_alminshawi', representation: 'segment' })`} action={() => getAyah({ ayah: '9:129', reciter: 'muhammad_alminshawi', representation: 'segment' })}><p>Network calls made: <b>1</b>. Moshaf identity, read-dependent shape, milliseconds, and the <code>www.</code> origin stay inside the adapter.</p></RunCard><RunCard title="MP3Quran-only class" code={`queryCatalog({ reciter: '${mpOnly.reciter}' })`} action={() => queryCatalog({ reciter: mpOnly.reciter })}><p>Fallback contributes nothing; this class has only MP3Quran bindings. Network calls made: <b>0</b>.</p></RunCard><RunCard title="Minshawi multi-source class" code={`getSurah({ surah: 55, recording: minshawi })`} action={() => getSurah({ surah: 55, recording: minshawi as RecordingClassRef })}><p>Default ranking chooses complete moshaf 112. The 26-surah 1387 source is reachable as a SourceRef and fails for surah 55. Network calls made: <b>0</b>.</p></RunCard><div className="card muted"><span className="tag warn">QF not yet implemented</span><p>No fixture replay or fake provider data exists in this app.</p></div></div></Section>
<Section number="6" title="Getting started"><div className="grid two"><div className="card"><Code>{`pnpm add quranic-audio-router\n\nimport { getAyah, Reciters } from 'quranic-audio-router'\nawait getAyah({ ayah: '1:2', recording: Reciters.MahmoudAlhusary.Hafs.Murattal })`}</Code><p>A configured client can set fetch, timeout, provider priority, and trace hooks.</p></div><div className="card"><h3>Server-only boundary</h3><p>Never put Quran Foundation credentials in browser code. QF belongs at <code>quranic-audio-router/server</code> once its adapters ship.</p><p className="note">Direct provider access exposes visitor IP address and listening activity. This playground does not prefetch or autoplay.</p><a className="pill" href="https://github.com/ebrahim-youssef/quranic-audio-router">Repository ↗</a></div></div></Section>
</main><footer><div className="shell">quranic-audio-router playground · provider calls are user-triggered.</div></footer></> }
